
package br.com.seta.processo.service.gestor.acesso.ws.consulta;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaPermissaoWS_V2", targetNamespace = "http://webservice.portal.seta.com.br/", wsdlLocation = "http://192.168.2.47:8080/gestordeacessos/ConsultaPermissaoWS_V2?wsdl")
public class ConsultaPermissaoWSV2_Service
    extends Service
{

    private final static URL CONSULTAPERMISSAOWSV2_WSDL_LOCATION;
    private final static WebServiceException CONSULTAPERMISSAOWSV2_EXCEPTION;
    private final static QName CONSULTAPERMISSAOWSV2_QNAME = new QName("http://webservice.portal.seta.com.br/", "ConsultaPermissaoWS_V2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.2.47:8080/gestordeacessos/ConsultaPermissaoWS_V2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAPERMISSAOWSV2_WSDL_LOCATION = url;
        CONSULTAPERMISSAOWSV2_EXCEPTION = e;
    }

    public ConsultaPermissaoWSV2_Service() {
        super(__getWsdlLocation(), CONSULTAPERMISSAOWSV2_QNAME);
    }

    public ConsultaPermissaoWSV2_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAPERMISSAOWSV2_QNAME, features);
    }

    public ConsultaPermissaoWSV2_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAPERMISSAOWSV2_QNAME);
    }

    public ConsultaPermissaoWSV2_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAPERMISSAOWSV2_QNAME, features);
    }

    public ConsultaPermissaoWSV2_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaPermissaoWSV2_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaPermissaoWSV2
     */
    @WebEndpoint(name = "ConsultaPermissaoWS_V2Port")
    public ConsultaPermissaoWSV2 getConsultaPermissaoWSV2Port() {
        return super.getPort(new QName("http://webservice.portal.seta.com.br/", "ConsultaPermissaoWS_V2Port"), ConsultaPermissaoWSV2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaPermissaoWSV2
     */
    @WebEndpoint(name = "ConsultaPermissaoWS_V2Port")
    public ConsultaPermissaoWSV2 getConsultaPermissaoWSV2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.portal.seta.com.br/", "ConsultaPermissaoWS_V2Port"), ConsultaPermissaoWSV2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAPERMISSAOWSV2_EXCEPTION!= null) {
            throw CONSULTAPERMISSAOWSV2_EXCEPTION;
        }
        return CONSULTAPERMISSAOWSV2_WSDL_LOCATION;
    }

}
