
package br.com.seta.processo.service.gestor.acesso.ws.consulta;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaPermissaoWS", targetNamespace = "http://webservice.portal.seta.com.br/", wsdlLocation = "http://192.168.2.47:8080/gestordeacessos/ConsultaPermissaoWS?wsdl")
public class ConsultaPermissaoWS_Service
    extends Service
{

    private final static URL CONSULTAPERMISSAOWS_WSDL_LOCATION;
    private final static WebServiceException CONSULTAPERMISSAOWS_EXCEPTION;
    private final static QName CONSULTAPERMISSAOWS_QNAME = new QName("http://webservice.portal.seta.com.br/", "ConsultaPermissaoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.2.47:8080/gestordeacessos/ConsultaPermissaoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAPERMISSAOWS_WSDL_LOCATION = url;
        CONSULTAPERMISSAOWS_EXCEPTION = e;
    }

    public ConsultaPermissaoWS_Service() {
        super(__getWsdlLocation(), CONSULTAPERMISSAOWS_QNAME);
    }

    public ConsultaPermissaoWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAPERMISSAOWS_QNAME, features);
    }

    public ConsultaPermissaoWS_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAPERMISSAOWS_QNAME);
    }

    public ConsultaPermissaoWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAPERMISSAOWS_QNAME, features);
    }

    public ConsultaPermissaoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaPermissaoWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaPermissaoWS
     */
    @WebEndpoint(name = "ConsultaPermissaoWSPort")
    public ConsultaPermissaoWS getConsultaPermissaoWSPort() {
        return super.getPort(new QName("http://webservice.portal.seta.com.br/", "ConsultaPermissaoWSPort"), ConsultaPermissaoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaPermissaoWS
     */
    @WebEndpoint(name = "ConsultaPermissaoWSPort")
    public ConsultaPermissaoWS getConsultaPermissaoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.portal.seta.com.br/", "ConsultaPermissaoWSPort"), ConsultaPermissaoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAPERMISSAOWS_EXCEPTION!= null) {
            throw CONSULTAPERMISSAOWS_EXCEPTION;
        }
        return CONSULTAPERMISSAOWS_WSDL_LOCATION;
    }

}
