package br.com.seta.processo.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrNfitensdespesaId generated by hbm2java
 */
@Embeddable
public class OrNfitensdespesaId implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private long seqnota;
	private short nroitem;

	public OrNfitensdespesaId() {
	}

	public OrNfitensdespesaId(long seqnota, short nroitem) {
		this.seqnota = seqnota;
		this.nroitem = nroitem;
	}

	@Column(name = "SEQNOTA", nullable = false, precision = 15, scale = 0)
	public long getSeqnota() {
		return this.seqnota;
	}

	public void setSeqnota(long seqnota) {
		this.seqnota = seqnota;
	}

	@Column(name = "NROITEM", nullable = false, precision = 3, scale = 0)
	public short getNroitem() {
		return this.nroitem;
	}

	public void setNroitem(short nroitem) {
		this.nroitem = nroitem;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrNfitensdespesaId))
			return false;
		OrNfitensdespesaId castOther = (OrNfitensdespesaId) other;

		return (this.getSeqnota() == castOther.getSeqnota())
				&& (this.getNroitem() == castOther.getNroitem());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSeqnota();
		result = 37 * result + this.getNroitem();
		return result;
	}

}
