package br.com.seta.processo.entity;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrNfplanilhalancto generated by hbm2java
 */
@Entity
@Table(name = "OR_NFPLANILHALANCTO")
public class OrNfplanilhalanctoEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private OrNfplanilhalanctoId id;
	private String nroplanilha;
	private short nroempresa;
	private short filial;
	private Long contadebito;
	private String tipoentidadedb;
	private Integer codentidadedb;
	private Integer centrocustodb;
	private Long contacredito;
	private String tipoentidadecr;
	private Integer codentidadecr;
	private Integer centrocustocr;
	private String historico;
	private BigDecimal vlrlancamento;
	private Date dtagerouctb;
	private String usugerouctb;
	private String situacao;
	private Long linkctb;
	private Long processoctb;
	private String menserro;
	private Date dtacontabiliza;
	private String tablink;
	private Long nrodocumento;
	private String descentidadedb;
	private String descentidadecr;
	private String tipocontab;
	private BigDecimal percrateio;
	private String historicooriginal;
	private String indorigemrequisicao;

	public OrNfplanilhalanctoEntity() {
	}

	public OrNfplanilhalanctoEntity(OrNfplanilhalanctoId id, String nroplanilha,
			short nroempresa, short filial) {
		this.id = id;
		this.nroplanilha = nroplanilha;
		this.nroempresa = nroempresa;
		this.filial = filial;
	}

	public OrNfplanilhalanctoEntity(OrNfplanilhalanctoId id, String nroplanilha,
			short nroempresa, short filial, Long contadebito,
			String tipoentidadedb, Integer codentidadedb,
			Integer centrocustodb, Long contacredito, String tipoentidadecr,
			Integer codentidadecr, Integer centrocustocr, String historico,
			BigDecimal vlrlancamento, Date dtagerouctb, String usugerouctb,
			String situacao, Long linkctb, Long processoctb, String menserro,
			Date dtacontabiliza, String tablink, Long nrodocumento,
			String descentidadedb, String descentidadecr, String tipocontab,
			BigDecimal percrateio, String historicooriginal,
			String indorigemrequisicao) {
		this.id = id;
		this.nroplanilha = nroplanilha;
		this.nroempresa = nroempresa;
		this.filial = filial;
		this.contadebito = contadebito;
		this.tipoentidadedb = tipoentidadedb;
		this.codentidadedb = codentidadedb;
		this.centrocustodb = centrocustodb;
		this.contacredito = contacredito;
		this.tipoentidadecr = tipoentidadecr;
		this.codentidadecr = codentidadecr;
		this.centrocustocr = centrocustocr;
		this.historico = historico;
		this.vlrlancamento = vlrlancamento;
		this.dtagerouctb = dtagerouctb;
		this.usugerouctb = usugerouctb;
		this.situacao = situacao;
		this.linkctb = linkctb;
		this.processoctb = processoctb;
		this.menserro = menserro;
		this.dtacontabiliza = dtacontabiliza;
		this.tablink = tablink;
		this.nrodocumento = nrodocumento;
		this.descentidadedb = descentidadedb;
		this.descentidadecr = descentidadecr;
		this.tipocontab = tipocontab;
		this.percrateio = percrateio;
		this.historicooriginal = historicooriginal;
		this.indorigemrequisicao = indorigemrequisicao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "seqnota", column = @Column(name = "SEQNOTA", nullable = false, precision = 15, scale = 0)),
			@AttributeOverride(name = "nrolinha", column = @Column(name = "NROLINHA", nullable = false, precision = 3, scale = 0)) })
	public OrNfplanilhalanctoId getId() {
		return this.id;
	}

	public void setId(OrNfplanilhalanctoId id) {
		this.id = id;
	}

	@Column(name = "NROPLANILHA", nullable = false, length = 12)
	public String getNroplanilha() {
		return this.nroplanilha;
	}

	public void setNroplanilha(String nroplanilha) {
		this.nroplanilha = nroplanilha;
	}

	@Column(name = "NROEMPRESA", nullable = false, precision = 3, scale = 0)
	public short getNroempresa() {
		return this.nroempresa;
	}

	public void setNroempresa(short nroempresa) {
		this.nroempresa = nroempresa;
	}

	@Column(name = "FILIAL", nullable = false, precision = 3, scale = 0)
	public short getFilial() {
		return this.filial;
	}

	public void setFilial(short filial) {
		this.filial = filial;
	}

	@Column(name = "CONTADEBITO", precision = 15, scale = 0)
	public Long getContadebito() {
		return this.contadebito;
	}

	public void setContadebito(Long contadebito) {
		this.contadebito = contadebito;
	}

	@Column(name = "TIPOENTIDADEDB", length = 2)
	public String getTipoentidadedb() {
		return this.tipoentidadedb;
	}

	public void setTipoentidadedb(String tipoentidadedb) {
		this.tipoentidadedb = tipoentidadedb;
	}

	@Column(name = "CODENTIDADEDB", precision = 8, scale = 0)
	public Integer getCodentidadedb() {
		return this.codentidadedb;
	}

	public void setCodentidadedb(Integer codentidadedb) {
		this.codentidadedb = codentidadedb;
	}

	@Column(name = "CENTROCUSTODB", precision = 6, scale = 0)
	public Integer getCentrocustodb() {
		return this.centrocustodb;
	}

	public void setCentrocustodb(Integer centrocustodb) {
		this.centrocustodb = centrocustodb;
	}

	@Column(name = "CONTACREDITO", precision = 15, scale = 0)
	public Long getContacredito() {
		return this.contacredito;
	}

	public void setContacredito(Long contacredito) {
		this.contacredito = contacredito;
	}

	@Column(name = "TIPOENTIDADECR", length = 2)
	public String getTipoentidadecr() {
		return this.tipoentidadecr;
	}

	public void setTipoentidadecr(String tipoentidadecr) {
		this.tipoentidadecr = tipoentidadecr;
	}

	@Column(name = "CODENTIDADECR", precision = 8, scale = 0)
	public Integer getCodentidadecr() {
		return this.codentidadecr;
	}

	public void setCodentidadecr(Integer codentidadecr) {
		this.codentidadecr = codentidadecr;
	}

	@Column(name = "CENTROCUSTOCR", precision = 6, scale = 0)
	public Integer getCentrocustocr() {
		return this.centrocustocr;
	}

	public void setCentrocustocr(Integer centrocustocr) {
		this.centrocustocr = centrocustocr;
	}

	@Column(name = "HISTORICO", length = 250)
	public String getHistorico() {
		return this.historico;
	}

	public void setHistorico(String historico) {
		this.historico = historico;
	}

	@Column(name = "VLRLANCAMENTO", precision = 15)
	public BigDecimal getVlrlancamento() {
		return this.vlrlancamento;
	}

	public void setVlrlancamento(BigDecimal vlrlancamento) {
		this.vlrlancamento = vlrlancamento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTAGEROUCTB", length = 7)
	public Date getDtagerouctb() {
		return this.dtagerouctb;
	}

	public void setDtagerouctb(Date dtagerouctb) {
		this.dtagerouctb = dtagerouctb;
	}

	@Column(name = "USUGEROUCTB", length = 12)
	public String getUsugerouctb() {
		return this.usugerouctb;
	}

	public void setUsugerouctb(String usugerouctb) {
		this.usugerouctb = usugerouctb;
	}

	@Column(name = "SITUACAO", length = 1)
	public String getSituacao() {
		return this.situacao;
	}

	public void setSituacao(String situacao) {
		this.situacao = situacao;
	}

	@Column(name = "LINKCTB", precision = 15, scale = 0)
	public Long getLinkctb() {
		return this.linkctb;
	}

	public void setLinkctb(Long linkctb) {
		this.linkctb = linkctb;
	}

	@Column(name = "PROCESSOCTB", precision = 15, scale = 0)
	public Long getProcessoctb() {
		return this.processoctb;
	}

	public void setProcessoctb(Long processoctb) {
		this.processoctb = processoctb;
	}

	@Column(name = "MENSERRO", length = 250)
	public String getMenserro() {
		return this.menserro;
	}

	public void setMenserro(String menserro) {
		this.menserro = menserro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTACONTABILIZA", length = 7)
	public Date getDtacontabiliza() {
		return this.dtacontabiliza;
	}

	public void setDtacontabiliza(Date dtacontabiliza) {
		this.dtacontabiliza = dtacontabiliza;
	}

	@Column(name = "TABLINK", length = 3)
	public String getTablink() {
		return this.tablink;
	}

	public void setTablink(String tablink) {
		this.tablink = tablink;
	}

	@Column(name = "NRODOCUMENTO", precision = 15, scale = 0)
	public Long getNrodocumento() {
		return this.nrodocumento;
	}

	public void setNrodocumento(Long nrodocumento) {
		this.nrodocumento = nrodocumento;
	}

	@Column(name = "DESCENTIDADEDB", length = 40)
	public String getDescentidadedb() {
		return this.descentidadedb;
	}

	public void setDescentidadedb(String descentidadedb) {
		this.descentidadedb = descentidadedb;
	}

	@Column(name = "DESCENTIDADECR", length = 40)
	public String getDescentidadecr() {
		return this.descentidadecr;
	}

	public void setDescentidadecr(String descentidadecr) {
		this.descentidadecr = descentidadecr;
	}

	@Column(name = "TIPOCONTAB", length = 1)
	public String getTipocontab() {
		return this.tipocontab;
	}

	public void setTipocontab(String tipocontab) {
		this.tipocontab = tipocontab;
	}

	@Column(name = "PERCRATEIO", precision = 7, scale = 4)
	public BigDecimal getPercrateio() {
		return this.percrateio;
	}

	public void setPercrateio(BigDecimal percrateio) {
		this.percrateio = percrateio;
	}

	@Column(name = "HISTORICOORIGINAL", length = 250)
	public String getHistoricooriginal() {
		return this.historicooriginal;
	}

	public void setHistoricooriginal(String historicooriginal) {
		this.historicooriginal = historicooriginal;
	}

	@Column(name = "INDORIGEMREQUISICAO", length = 1)
	public String getIndorigemrequisicao() {
		return this.indorigemrequisicao;
	}

	public void setIndorigemrequisicao(String indorigemrequisicao) {
		this.indorigemrequisicao = indorigemrequisicao;
	}

}
