package br.com.seta.processo.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrNfplanilhalanctoId generated by hbm2java
 */
@Embeddable
public class OrNfplanilhalanctoId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private long seqnota;
	private short nrolinha;

	public OrNfplanilhalanctoId() {
	}

	public OrNfplanilhalanctoId(long seqnota, short nrolinha) {
		this.seqnota = seqnota;
		this.nrolinha = nrolinha;
	}

	@Column(name = "SEQNOTA", nullable = false, precision = 15, scale = 0)
	public long getSeqnota() {
		return this.seqnota;
	}

	public void setSeqnota(long seqnota) {
		this.seqnota = seqnota;
	}

	@Column(name = "NROLINHA", nullable = false, precision = 3, scale = 0)
	public short getNrolinha() {
		return this.nrolinha;
	}

	public void setNrolinha(short nrolinha) {
		this.nrolinha = nrolinha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrNfplanilhalanctoId))
			return false;
		OrNfplanilhalanctoId castOther = (OrNfplanilhalanctoId) other;

		return (this.getSeqnota() == castOther.getSeqnota())
				&& (this.getNrolinha() == castOther.getNrolinha());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSeqnota();
		result = 37 * result + this.getNrolinha();
		return result;
	}

}
