package br.com.seta.processo.entity;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrParametro generated by hbm2java
 */
@Entity
@Table(name = "OR_PARAMETRO")
public class OrParametroEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private short nroempresa;
	private short nroempresaorc;
	private String tipoorc;
	private BigDecimal percinss;
	private BigDecimal percir;
	private BigDecimal percpis;
	private BigDecimal perccofins;
	private BigDecimal percissst;
	private BigDecimal perccssll;
	private String usaautorizacao;
	private Short codopdesconto;
	private short codopacrescimos;
	private String codespecieinss;
	private Integer seqpessoainss;
	private Short codoperacaoinss;
	private String codespecieir;
	private Integer seqpessoair;
	private Short codoperacaoir;
	private String codespeciepis;
	private Integer seqpessoapis;
	private Short codoperacaopis;
	private String codespecieissst;
	private Integer seqpessoaissst;
	private Short codoperacaoissst;
	private String codespeciecofins;
	private Integer seqpessoacofins;
	private Short codoperacaocofins;
	private String codespeciecssll;
	private Integer seqpessoacssll;
	private Short codoperacaocssll;
	private BigDecimal perissqn;
	private String codespecieissqn;
	private Short codoperacaoissqn;
	private Integer seqpessoaissqn;
	private BigDecimal percicms;
	private String codespecieicms;
	private Short codoperacaoicms;
	private Integer seqpessoaicms;
	private String tipodtacontrole;
	private BigDecimal percsestsenat;
	private String codespeciesestsenat;
	private Short codoperacaosestsenat;
	private Integer seqpessoasestsenat;
	private String usaseguranctaorcam;
	private String usasegurannatdesp;
	private String usaalcadaautorizacao;
	private String tipodesconto;
	private BigDecimal percipi;
	private String codespecieipi;
	private Integer seqpessoaipi;
	private Short codoperacaoipi;
	private String empverba;
	private String gertitagruppiscofinscsll;
	private String codespagruppiscofinscsll;
	private String pessoaagruppiscofinscsll;
	private String codopagruppiscofinscsll;
	private String usualteracao;
	private Date dtaalteracao;
	private String situacaonfpis;
	private String situacaonfcofins;
	private Long seqpadraovenctoinss;
	private Long seqpadraovenctopis;
	private Long seqpadraovenctocofins;
	private Long seqpadraovenctocssll;
	private Long seqpadraovenctoicms;
	private Long seqpadraovenctoir;
	private Long seqpadraovenctoissst;
	private Long seqpadraovenctoissqn;
	private Long seqpadraovenctosestsenat;
	private Long seqpadraovenctoipi;
	private String usasegurancentroresult;
	private String usagruponatdesp;
	private String inddiautildtavenc;
	private String codespecieicmsrettransp;
	private Integer seqpessoaicmsrettransp;
	private Integer codoperacaoicmsrettransp;
	private Long seqpadraovenctoicmsrettransp;
	private BigDecimal percicmsrettransp;
	private Long codrecdarfpisret;
	private Long codrecdarfcofinsret;
	private Long codrecdarfcsllret;
	private Long codrecdarftodosret;
	private Long seqpadraovenctoinsspat;
	private BigDecimal percinsspat;
	private String codespecieinsspat;
	private Integer seqpessoainsspat;
	private Short codoperacaoinsspat;
	private String indintegradtafutura;
	private String indcontroleorcamentario;
	private String indutilizamultireqnf;
	private String indcontabilizavlrnf;
	private String usaarvoreautalcada;
	private String indperiodoorc;
	private String indcontroleorc;
	private BigDecimal percirpesfis;
	private String codespecieirpesfis;
	private Integer seqpessoairpesfis;
	private Short codoperacaoirpesfis;
	private Long seqpadraovenctoirpesfis;
	private BigDecimal percinsspesfis;
	private String codespecieinsspesfis;
	private Integer seqpessoainsspesfis;
	private Short codoperacaoinsspesfis;
	private Long seqpadraovenctoinsspesfis;
	private String procorcpercentual;

	public OrParametroEntity() {
	}

	public OrParametroEntity(short nroempresa, short nroempresaorc, String tipoorc,
			BigDecimal percinss, BigDecimal percir, BigDecimal percpis,
			BigDecimal perccofins, BigDecimal percissst, BigDecimal perccssll,
			short codopacrescimos, BigDecimal percsestsenat,
			String tipodesconto, String usagruponatdesp,
			String inddiautildtavenc) {
		this.nroempresa = nroempresa;
		this.nroempresaorc = nroempresaorc;
		this.tipoorc = tipoorc;
		this.percinss = percinss;
		this.percir = percir;
		this.percpis = percpis;
		this.perccofins = perccofins;
		this.percissst = percissst;
		this.perccssll = perccssll;
		this.codopacrescimos = codopacrescimos;
		this.percsestsenat = percsestsenat;
		this.tipodesconto = tipodesconto;
		this.usagruponatdesp = usagruponatdesp;
		this.inddiautildtavenc = inddiautildtavenc;
	}

	public OrParametroEntity(short nroempresa, short nroempresaorc, String tipoorc,
			BigDecimal percinss, BigDecimal percir, BigDecimal percpis,
			BigDecimal perccofins, BigDecimal percissst, BigDecimal perccssll,
			String usaautorizacao, Short codopdesconto, short codopacrescimos,
			String codespecieinss, Integer seqpessoainss,
			Short codoperacaoinss, String codespecieir, Integer seqpessoair,
			Short codoperacaoir, String codespeciepis, Integer seqpessoapis,
			Short codoperacaopis, String codespecieissst,
			Integer seqpessoaissst, Short codoperacaoissst,
			String codespeciecofins, Integer seqpessoacofins,
			Short codoperacaocofins, String codespeciecssll,
			Integer seqpessoacssll, Short codoperacaocssll,
			BigDecimal perissqn, String codespecieissqn,
			Short codoperacaoissqn, Integer seqpessoaissqn,
			BigDecimal percicms, String codespecieicms, Short codoperacaoicms,
			Integer seqpessoaicms, String tipodtacontrole,
			BigDecimal percsestsenat, String codespeciesestsenat,
			Short codoperacaosestsenat, Integer seqpessoasestsenat,
			String usaseguranctaorcam, String usasegurannatdesp,
			String usaalcadaautorizacao, String tipodesconto,
			BigDecimal percipi, String codespecieipi, Integer seqpessoaipi,
			Short codoperacaoipi, String empverba,
			String gertitagruppiscofinscsll, String codespagruppiscofinscsll,
			String pessoaagruppiscofinscsll, String codopagruppiscofinscsll,
			String usualteracao, Date dtaalteracao, String situacaonfpis,
			String situacaonfcofins, Long seqpadraovenctoinss,
			Long seqpadraovenctopis, Long seqpadraovenctocofins,
			Long seqpadraovenctocssll, Long seqpadraovenctoicms,
			Long seqpadraovenctoir, Long seqpadraovenctoissst,
			Long seqpadraovenctoissqn, Long seqpadraovenctosestsenat,
			Long seqpadraovenctoipi, String usasegurancentroresult,
			String usagruponatdesp, String inddiautildtavenc,
			String codespecieicmsrettransp, Integer seqpessoaicmsrettransp,
			Integer codoperacaoicmsrettransp,
			Long seqpadraovenctoicmsrettransp, BigDecimal percicmsrettransp,
			Long codrecdarfpisret, Long codrecdarfcofinsret,
			Long codrecdarfcsllret, Long codrecdarftodosret,
			Long seqpadraovenctoinsspat, BigDecimal percinsspat,
			String codespecieinsspat, Integer seqpessoainsspat,
			Short codoperacaoinsspat, String indintegradtafutura,
			String indcontroleorcamentario, String indutilizamultireqnf,
			String indcontabilizavlrnf, String usaarvoreautalcada,
			String indperiodoorc, String indcontroleorc,
			BigDecimal percirpesfis, String codespecieirpesfis,
			Integer seqpessoairpesfis, Short codoperacaoirpesfis,
			Long seqpadraovenctoirpesfis, BigDecimal percinsspesfis,
			String codespecieinsspesfis, Integer seqpessoainsspesfis,
			Short codoperacaoinsspesfis, Long seqpadraovenctoinsspesfis,
			String procorcpercentual) {
		this.nroempresa = nroempresa;
		this.nroempresaorc = nroempresaorc;
		this.tipoorc = tipoorc;
		this.percinss = percinss;
		this.percir = percir;
		this.percpis = percpis;
		this.perccofins = perccofins;
		this.percissst = percissst;
		this.perccssll = perccssll;
		this.usaautorizacao = usaautorizacao;
		this.codopdesconto = codopdesconto;
		this.codopacrescimos = codopacrescimos;
		this.codespecieinss = codespecieinss;
		this.seqpessoainss = seqpessoainss;
		this.codoperacaoinss = codoperacaoinss;
		this.codespecieir = codespecieir;
		this.seqpessoair = seqpessoair;
		this.codoperacaoir = codoperacaoir;
		this.codespeciepis = codespeciepis;
		this.seqpessoapis = seqpessoapis;
		this.codoperacaopis = codoperacaopis;
		this.codespecieissst = codespecieissst;
		this.seqpessoaissst = seqpessoaissst;
		this.codoperacaoissst = codoperacaoissst;
		this.codespeciecofins = codespeciecofins;
		this.seqpessoacofins = seqpessoacofins;
		this.codoperacaocofins = codoperacaocofins;
		this.codespeciecssll = codespeciecssll;
		this.seqpessoacssll = seqpessoacssll;
		this.codoperacaocssll = codoperacaocssll;
		this.perissqn = perissqn;
		this.codespecieissqn = codespecieissqn;
		this.codoperacaoissqn = codoperacaoissqn;
		this.seqpessoaissqn = seqpessoaissqn;
		this.percicms = percicms;
		this.codespecieicms = codespecieicms;
		this.codoperacaoicms = codoperacaoicms;
		this.seqpessoaicms = seqpessoaicms;
		this.tipodtacontrole = tipodtacontrole;
		this.percsestsenat = percsestsenat;
		this.codespeciesestsenat = codespeciesestsenat;
		this.codoperacaosestsenat = codoperacaosestsenat;
		this.seqpessoasestsenat = seqpessoasestsenat;
		this.usaseguranctaorcam = usaseguranctaorcam;
		this.usasegurannatdesp = usasegurannatdesp;
		this.usaalcadaautorizacao = usaalcadaautorizacao;
		this.tipodesconto = tipodesconto;
		this.percipi = percipi;
		this.codespecieipi = codespecieipi;
		this.seqpessoaipi = seqpessoaipi;
		this.codoperacaoipi = codoperacaoipi;
		this.empverba = empverba;
		this.gertitagruppiscofinscsll = gertitagruppiscofinscsll;
		this.codespagruppiscofinscsll = codespagruppiscofinscsll;
		this.pessoaagruppiscofinscsll = pessoaagruppiscofinscsll;
		this.codopagruppiscofinscsll = codopagruppiscofinscsll;
		this.usualteracao = usualteracao;
		this.dtaalteracao = dtaalteracao;
		this.situacaonfpis = situacaonfpis;
		this.situacaonfcofins = situacaonfcofins;
		this.seqpadraovenctoinss = seqpadraovenctoinss;
		this.seqpadraovenctopis = seqpadraovenctopis;
		this.seqpadraovenctocofins = seqpadraovenctocofins;
		this.seqpadraovenctocssll = seqpadraovenctocssll;
		this.seqpadraovenctoicms = seqpadraovenctoicms;
		this.seqpadraovenctoir = seqpadraovenctoir;
		this.seqpadraovenctoissst = seqpadraovenctoissst;
		this.seqpadraovenctoissqn = seqpadraovenctoissqn;
		this.seqpadraovenctosestsenat = seqpadraovenctosestsenat;
		this.seqpadraovenctoipi = seqpadraovenctoipi;
		this.usasegurancentroresult = usasegurancentroresult;
		this.usagruponatdesp = usagruponatdesp;
		this.inddiautildtavenc = inddiautildtavenc;
		this.codespecieicmsrettransp = codespecieicmsrettransp;
		this.seqpessoaicmsrettransp = seqpessoaicmsrettransp;
		this.codoperacaoicmsrettransp = codoperacaoicmsrettransp;
		this.seqpadraovenctoicmsrettransp = seqpadraovenctoicmsrettransp;
		this.percicmsrettransp = percicmsrettransp;
		this.codrecdarfpisret = codrecdarfpisret;
		this.codrecdarfcofinsret = codrecdarfcofinsret;
		this.codrecdarfcsllret = codrecdarfcsllret;
		this.codrecdarftodosret = codrecdarftodosret;
		this.seqpadraovenctoinsspat = seqpadraovenctoinsspat;
		this.percinsspat = percinsspat;
		this.codespecieinsspat = codespecieinsspat;
		this.seqpessoainsspat = seqpessoainsspat;
		this.codoperacaoinsspat = codoperacaoinsspat;
		this.indintegradtafutura = indintegradtafutura;
		this.indcontroleorcamentario = indcontroleorcamentario;
		this.indutilizamultireqnf = indutilizamultireqnf;
		this.indcontabilizavlrnf = indcontabilizavlrnf;
		this.usaarvoreautalcada = usaarvoreautalcada;
		this.indperiodoorc = indperiodoorc;
		this.indcontroleorc = indcontroleorc;
		this.percirpesfis = percirpesfis;
		this.codespecieirpesfis = codespecieirpesfis;
		this.seqpessoairpesfis = seqpessoairpesfis;
		this.codoperacaoirpesfis = codoperacaoirpesfis;
		this.seqpadraovenctoirpesfis = seqpadraovenctoirpesfis;
		this.percinsspesfis = percinsspesfis;
		this.codespecieinsspesfis = codespecieinsspesfis;
		this.seqpessoainsspesfis = seqpessoainsspesfis;
		this.codoperacaoinsspesfis = codoperacaoinsspesfis;
		this.seqpadraovenctoinsspesfis = seqpadraovenctoinsspesfis;
		this.procorcpercentual = procorcpercentual;
	}

	@Id
	@Column(name = "NROEMPRESA", unique = true, nullable = false, precision = 3, scale = 0)
	public short getNroempresa() {
		return this.nroempresa;
	}

	public void setNroempresa(short nroempresa) {
		this.nroempresa = nroempresa;
	}

	@Column(name = "NROEMPRESAORC", nullable = false, precision = 3, scale = 0)
	public short getNroempresaorc() {
		return this.nroempresaorc;
	}

	public void setNroempresaorc(short nroempresaorc) {
		this.nroempresaorc = nroempresaorc;
	}

	@Column(name = "TIPOORC", nullable = false, length = 1)
	public String getTipoorc() {
		return this.tipoorc;
	}

	public void setTipoorc(String tipoorc) {
		this.tipoorc = tipoorc;
	}

	@Column(name = "PERCINSS", nullable = false, precision = 5)
	public BigDecimal getPercinss() {
		return this.percinss;
	}

	public void setPercinss(BigDecimal percinss) {
		this.percinss = percinss;
	}

	@Column(name = "PERCIR", nullable = false, precision = 5)
	public BigDecimal getPercir() {
		return this.percir;
	}

	public void setPercir(BigDecimal percir) {
		this.percir = percir;
	}

	@Column(name = "PERCPIS", nullable = false, precision = 7, scale = 4)
	public BigDecimal getPercpis() {
		return this.percpis;
	}

	public void setPercpis(BigDecimal percpis) {
		this.percpis = percpis;
	}

	@Column(name = "PERCCOFINS", nullable = false, precision = 7, scale = 4)
	public BigDecimal getPerccofins() {
		return this.perccofins;
	}

	public void setPerccofins(BigDecimal perccofins) {
		this.perccofins = perccofins;
	}

	@Column(name = "PERCISSST", nullable = false, precision = 5)
	public BigDecimal getPercissst() {
		return this.percissst;
	}

	public void setPercissst(BigDecimal percissst) {
		this.percissst = percissst;
	}

	@Column(name = "PERCCSSLL", nullable = false, precision = 5)
	public BigDecimal getPerccssll() {
		return this.perccssll;
	}

	public void setPerccssll(BigDecimal perccssll) {
		this.perccssll = perccssll;
	}

	@Column(name = "USAAUTORIZACAO", length = 1)
	public String getUsaautorizacao() {
		return this.usaautorizacao;
	}

	public void setUsaautorizacao(String usaautorizacao) {
		this.usaautorizacao = usaautorizacao;
	}

	@Column(name = "CODOPDESCONTO", precision = 4, scale = 0)
	public Short getCodopdesconto() {
		return this.codopdesconto;
	}

	public void setCodopdesconto(Short codopdesconto) {
		this.codopdesconto = codopdesconto;
	}

	@Column(name = "CODOPACRESCIMOS", nullable = false, precision = 4, scale = 0)
	public short getCodopacrescimos() {
		return this.codopacrescimos;
	}

	public void setCodopacrescimos(short codopacrescimos) {
		this.codopacrescimos = codopacrescimos;
	}

	@Column(name = "CODESPECIEINSS", length = 6)
	public String getCodespecieinss() {
		return this.codespecieinss;
	}

	public void setCodespecieinss(String codespecieinss) {
		this.codespecieinss = codespecieinss;
	}

	@Column(name = "SEQPESSOAINSS", precision = 8, scale = 0)
	public Integer getSeqpessoainss() {
		return this.seqpessoainss;
	}

	public void setSeqpessoainss(Integer seqpessoainss) {
		this.seqpessoainss = seqpessoainss;
	}

	@Column(name = "CODOPERACAOINSS", precision = 3, scale = 0)
	public Short getCodoperacaoinss() {
		return this.codoperacaoinss;
	}

	public void setCodoperacaoinss(Short codoperacaoinss) {
		this.codoperacaoinss = codoperacaoinss;
	}

	@Column(name = "CODESPECIEIR", length = 6)
	public String getCodespecieir() {
		return this.codespecieir;
	}

	public void setCodespecieir(String codespecieir) {
		this.codespecieir = codespecieir;
	}

	@Column(name = "SEQPESSOAIR", precision = 8, scale = 0)
	public Integer getSeqpessoair() {
		return this.seqpessoair;
	}

	public void setSeqpessoair(Integer seqpessoair) {
		this.seqpessoair = seqpessoair;
	}

	@Column(name = "CODOPERACAOIR", precision = 3, scale = 0)
	public Short getCodoperacaoir() {
		return this.codoperacaoir;
	}

	public void setCodoperacaoir(Short codoperacaoir) {
		this.codoperacaoir = codoperacaoir;
	}

	@Column(name = "CODESPECIEPIS", length = 6)
	public String getCodespeciepis() {
		return this.codespeciepis;
	}

	public void setCodespeciepis(String codespeciepis) {
		this.codespeciepis = codespeciepis;
	}

	@Column(name = "SEQPESSOAPIS", precision = 8, scale = 0)
	public Integer getSeqpessoapis() {
		return this.seqpessoapis;
	}

	public void setSeqpessoapis(Integer seqpessoapis) {
		this.seqpessoapis = seqpessoapis;
	}

	@Column(name = "CODOPERACAOPIS", precision = 3, scale = 0)
	public Short getCodoperacaopis() {
		return this.codoperacaopis;
	}

	public void setCodoperacaopis(Short codoperacaopis) {
		this.codoperacaopis = codoperacaopis;
	}

	@Column(name = "CODESPECIEISSST", length = 6)
	public String getCodespecieissst() {
		return this.codespecieissst;
	}

	public void setCodespecieissst(String codespecieissst) {
		this.codespecieissst = codespecieissst;
	}

	@Column(name = "SEQPESSOAISSST", precision = 8, scale = 0)
	public Integer getSeqpessoaissst() {
		return this.seqpessoaissst;
	}

	public void setSeqpessoaissst(Integer seqpessoaissst) {
		this.seqpessoaissst = seqpessoaissst;
	}

	@Column(name = "CODOPERACAOISSST", precision = 3, scale = 0)
	public Short getCodoperacaoissst() {
		return this.codoperacaoissst;
	}

	public void setCodoperacaoissst(Short codoperacaoissst) {
		this.codoperacaoissst = codoperacaoissst;
	}

	@Column(name = "CODESPECIECOFINS", length = 6)
	public String getCodespeciecofins() {
		return this.codespeciecofins;
	}

	public void setCodespeciecofins(String codespeciecofins) {
		this.codespeciecofins = codespeciecofins;
	}

	@Column(name = "SEQPESSOACOFINS", precision = 8, scale = 0)
	public Integer getSeqpessoacofins() {
		return this.seqpessoacofins;
	}

	public void setSeqpessoacofins(Integer seqpessoacofins) {
		this.seqpessoacofins = seqpessoacofins;
	}

	@Column(name = "CODOPERACAOCOFINS", precision = 3, scale = 0)
	public Short getCodoperacaocofins() {
		return this.codoperacaocofins;
	}

	public void setCodoperacaocofins(Short codoperacaocofins) {
		this.codoperacaocofins = codoperacaocofins;
	}

	@Column(name = "CODESPECIECSSLL", length = 6)
	public String getCodespeciecssll() {
		return this.codespeciecssll;
	}

	public void setCodespeciecssll(String codespeciecssll) {
		this.codespeciecssll = codespeciecssll;
	}

	@Column(name = "SEQPESSOACSSLL", precision = 8, scale = 0)
	public Integer getSeqpessoacssll() {
		return this.seqpessoacssll;
	}

	public void setSeqpessoacssll(Integer seqpessoacssll) {
		this.seqpessoacssll = seqpessoacssll;
	}

	@Column(name = "CODOPERACAOCSSLL", precision = 3, scale = 0)
	public Short getCodoperacaocssll() {
		return this.codoperacaocssll;
	}

	public void setCodoperacaocssll(Short codoperacaocssll) {
		this.codoperacaocssll = codoperacaocssll;
	}

	@Column(name = "PERISSQN", precision = 5)
	public BigDecimal getPerissqn() {
		return this.perissqn;
	}

	public void setPerissqn(BigDecimal perissqn) {
		this.perissqn = perissqn;
	}

	@Column(name = "CODESPECIEISSQN", length = 6)
	public String getCodespecieissqn() {
		return this.codespecieissqn;
	}

	public void setCodespecieissqn(String codespecieissqn) {
		this.codespecieissqn = codespecieissqn;
	}

	@Column(name = "CODOPERACAOISSQN", precision = 3, scale = 0)
	public Short getCodoperacaoissqn() {
		return this.codoperacaoissqn;
	}

	public void setCodoperacaoissqn(Short codoperacaoissqn) {
		this.codoperacaoissqn = codoperacaoissqn;
	}

	@Column(name = "SEQPESSOAISSQN", precision = 8, scale = 0)
	public Integer getSeqpessoaissqn() {
		return this.seqpessoaissqn;
	}

	public void setSeqpessoaissqn(Integer seqpessoaissqn) {
		this.seqpessoaissqn = seqpessoaissqn;
	}

	@Column(name = "PERCICMS", precision = 5)
	public BigDecimal getPercicms() {
		return this.percicms;
	}

	public void setPercicms(BigDecimal percicms) {
		this.percicms = percicms;
	}

	@Column(name = "CODESPECIEICMS", length = 6)
	public String getCodespecieicms() {
		return this.codespecieicms;
	}

	public void setCodespecieicms(String codespecieicms) {
		this.codespecieicms = codespecieicms;
	}

	@Column(name = "CODOPERACAOICMS", precision = 3, scale = 0)
	public Short getCodoperacaoicms() {
		return this.codoperacaoicms;
	}

	public void setCodoperacaoicms(Short codoperacaoicms) {
		this.codoperacaoicms = codoperacaoicms;
	}

	@Column(name = "SEQPESSOAICMS", precision = 8, scale = 0)
	public Integer getSeqpessoaicms() {
		return this.seqpessoaicms;
	}

	public void setSeqpessoaicms(Integer seqpessoaicms) {
		this.seqpessoaicms = seqpessoaicms;
	}

	@Column(name = "TIPODTACONTROLE", length = 1)
	public String getTipodtacontrole() {
		return this.tipodtacontrole;
	}

	public void setTipodtacontrole(String tipodtacontrole) {
		this.tipodtacontrole = tipodtacontrole;
	}

	@Column(name = "PERCSESTSENAT", nullable = false, precision = 5)
	public BigDecimal getPercsestsenat() {
		return this.percsestsenat;
	}

	public void setPercsestsenat(BigDecimal percsestsenat) {
		this.percsestsenat = percsestsenat;
	}

	@Column(name = "CODESPECIESESTSENAT", length = 6)
	public String getCodespeciesestsenat() {
		return this.codespeciesestsenat;
	}

	public void setCodespeciesestsenat(String codespeciesestsenat) {
		this.codespeciesestsenat = codespeciesestsenat;
	}

	@Column(name = "CODOPERACAOSESTSENAT", precision = 3, scale = 0)
	public Short getCodoperacaosestsenat() {
		return this.codoperacaosestsenat;
	}

	public void setCodoperacaosestsenat(Short codoperacaosestsenat) {
		this.codoperacaosestsenat = codoperacaosestsenat;
	}

	@Column(name = "SEQPESSOASESTSENAT", precision = 8, scale = 0)
	public Integer getSeqpessoasestsenat() {
		return this.seqpessoasestsenat;
	}

	public void setSeqpessoasestsenat(Integer seqpessoasestsenat) {
		this.seqpessoasestsenat = seqpessoasestsenat;
	}

	@Column(name = "USASEGURANCTAORCAM", length = 1)
	public String getUsaseguranctaorcam() {
		return this.usaseguranctaorcam;
	}

	public void setUsaseguranctaorcam(String usaseguranctaorcam) {
		this.usaseguranctaorcam = usaseguranctaorcam;
	}

	@Column(name = "USASEGURANNATDESP", length = 1)
	public String getUsasegurannatdesp() {
		return this.usasegurannatdesp;
	}

	public void setUsasegurannatdesp(String usasegurannatdesp) {
		this.usasegurannatdesp = usasegurannatdesp;
	}

	@Column(name = "USAALCADAAUTORIZACAO", length = 1)
	public String getUsaalcadaautorizacao() {
		return this.usaalcadaautorizacao;
	}

	public void setUsaalcadaautorizacao(String usaalcadaautorizacao) {
		this.usaalcadaautorizacao = usaalcadaautorizacao;
	}

	@Column(name = "TIPODESCONTO", nullable = false, length = 1)
	public String getTipodesconto() {
		return this.tipodesconto;
	}

	public void setTipodesconto(String tipodesconto) {
		this.tipodesconto = tipodesconto;
	}

	@Column(name = "PERCIPI", precision = 5)
	public BigDecimal getPercipi() {
		return this.percipi;
	}

	public void setPercipi(BigDecimal percipi) {
		this.percipi = percipi;
	}

	@Column(name = "CODESPECIEIPI", length = 6)
	public String getCodespecieipi() {
		return this.codespecieipi;
	}

	public void setCodespecieipi(String codespecieipi) {
		this.codespecieipi = codespecieipi;
	}

	@Column(name = "SEQPESSOAIPI", precision = 8, scale = 0)
	public Integer getSeqpessoaipi() {
		return this.seqpessoaipi;
	}

	public void setSeqpessoaipi(Integer seqpessoaipi) {
		this.seqpessoaipi = seqpessoaipi;
	}

	@Column(name = "CODOPERACAOIPI", precision = 3, scale = 0)
	public Short getCodoperacaoipi() {
		return this.codoperacaoipi;
	}

	public void setCodoperacaoipi(Short codoperacaoipi) {
		this.codoperacaoipi = codoperacaoipi;
	}

	@Column(name = "EMPVERBA", length = 1)
	public String getEmpverba() {
		return this.empverba;
	}

	public void setEmpverba(String empverba) {
		this.empverba = empverba;
	}

	@Column(name = "GERTITAGRUPPISCOFINSCSLL", length = 1)
	public String getGertitagruppiscofinscsll() {
		return this.gertitagruppiscofinscsll;
	}

	public void setGertitagruppiscofinscsll(String gertitagruppiscofinscsll) {
		this.gertitagruppiscofinscsll = gertitagruppiscofinscsll;
	}

	@Column(name = "CODESPAGRUPPISCOFINSCSLL", length = 6)
	public String getCodespagruppiscofinscsll() {
		return this.codespagruppiscofinscsll;
	}

	public void setCodespagruppiscofinscsll(String codespagruppiscofinscsll) {
		this.codespagruppiscofinscsll = codespagruppiscofinscsll;
	}

	@Column(name = "PESSOAAGRUPPISCOFINSCSLL", length = 8)
	public String getPessoaagruppiscofinscsll() {
		return this.pessoaagruppiscofinscsll;
	}

	public void setPessoaagruppiscofinscsll(String pessoaagruppiscofinscsll) {
		this.pessoaagruppiscofinscsll = pessoaagruppiscofinscsll;
	}

	@Column(name = "CODOPAGRUPPISCOFINSCSLL", length = 3)
	public String getCodopagruppiscofinscsll() {
		return this.codopagruppiscofinscsll;
	}

	public void setCodopagruppiscofinscsll(String codopagruppiscofinscsll) {
		this.codopagruppiscofinscsll = codopagruppiscofinscsll;
	}

	@Column(name = "USUALTERACAO", length = 12)
	public String getUsualteracao() {
		return this.usualteracao;
	}

	public void setUsualteracao(String usualteracao) {
		this.usualteracao = usualteracao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTAALTERACAO", length = 7)
	public Date getDtaalteracao() {
		return this.dtaalteracao;
	}

	public void setDtaalteracao(Date dtaalteracao) {
		this.dtaalteracao = dtaalteracao;
	}

	@Column(name = "SITUACAONFPIS", length = 2)
	public String getSituacaonfpis() {
		return this.situacaonfpis;
	}

	public void setSituacaonfpis(String situacaonfpis) {
		this.situacaonfpis = situacaonfpis;
	}

	@Column(name = "SITUACAONFCOFINS", length = 2)
	public String getSituacaonfcofins() {
		return this.situacaonfcofins;
	}

	public void setSituacaonfcofins(String situacaonfcofins) {
		this.situacaonfcofins = situacaonfcofins;
	}

	@Column(name = "SEQPADRAOVENCTOINSS", precision = 15, scale = 0)
	public Long getSeqpadraovenctoinss() {
		return this.seqpadraovenctoinss;
	}

	public void setSeqpadraovenctoinss(Long seqpadraovenctoinss) {
		this.seqpadraovenctoinss = seqpadraovenctoinss;
	}

	@Column(name = "SEQPADRAOVENCTOPIS", precision = 15, scale = 0)
	public Long getSeqpadraovenctopis() {
		return this.seqpadraovenctopis;
	}

	public void setSeqpadraovenctopis(Long seqpadraovenctopis) {
		this.seqpadraovenctopis = seqpadraovenctopis;
	}

	@Column(name = "SEQPADRAOVENCTOCOFINS", precision = 15, scale = 0)
	public Long getSeqpadraovenctocofins() {
		return this.seqpadraovenctocofins;
	}

	public void setSeqpadraovenctocofins(Long seqpadraovenctocofins) {
		this.seqpadraovenctocofins = seqpadraovenctocofins;
	}

	@Column(name = "SEQPADRAOVENCTOCSSLL", precision = 15, scale = 0)
	public Long getSeqpadraovenctocssll() {
		return this.seqpadraovenctocssll;
	}

	public void setSeqpadraovenctocssll(Long seqpadraovenctocssll) {
		this.seqpadraovenctocssll = seqpadraovenctocssll;
	}

	@Column(name = "SEQPADRAOVENCTOICMS", precision = 15, scale = 0)
	public Long getSeqpadraovenctoicms() {
		return this.seqpadraovenctoicms;
	}

	public void setSeqpadraovenctoicms(Long seqpadraovenctoicms) {
		this.seqpadraovenctoicms = seqpadraovenctoicms;
	}

	@Column(name = "SEQPADRAOVENCTOIR", precision = 15, scale = 0)
	public Long getSeqpadraovenctoir() {
		return this.seqpadraovenctoir;
	}

	public void setSeqpadraovenctoir(Long seqpadraovenctoir) {
		this.seqpadraovenctoir = seqpadraovenctoir;
	}

	@Column(name = "SEQPADRAOVENCTOISSST", precision = 15, scale = 0)
	public Long getSeqpadraovenctoissst() {
		return this.seqpadraovenctoissst;
	}

	public void setSeqpadraovenctoissst(Long seqpadraovenctoissst) {
		this.seqpadraovenctoissst = seqpadraovenctoissst;
	}

	@Column(name = "SEQPADRAOVENCTOISSQN", precision = 15, scale = 0)
	public Long getSeqpadraovenctoissqn() {
		return this.seqpadraovenctoissqn;
	}

	public void setSeqpadraovenctoissqn(Long seqpadraovenctoissqn) {
		this.seqpadraovenctoissqn = seqpadraovenctoissqn;
	}

	@Column(name = "SEQPADRAOVENCTOSESTSENAT", precision = 15, scale = 0)
	public Long getSeqpadraovenctosestsenat() {
		return this.seqpadraovenctosestsenat;
	}

	public void setSeqpadraovenctosestsenat(Long seqpadraovenctosestsenat) {
		this.seqpadraovenctosestsenat = seqpadraovenctosestsenat;
	}

	@Column(name = "SEQPADRAOVENCTOIPI", precision = 15, scale = 0)
	public Long getSeqpadraovenctoipi() {
		return this.seqpadraovenctoipi;
	}

	public void setSeqpadraovenctoipi(Long seqpadraovenctoipi) {
		this.seqpadraovenctoipi = seqpadraovenctoipi;
	}

	@Column(name = "USASEGURANCENTRORESULT", length = 1)
	public String getUsasegurancentroresult() {
		return this.usasegurancentroresult;
	}

	public void setUsasegurancentroresult(String usasegurancentroresult) {
		this.usasegurancentroresult = usasegurancentroresult;
	}

	@Column(name = "USAGRUPONATDESP", nullable = false, length = 1)
	public String getUsagruponatdesp() {
		return this.usagruponatdesp;
	}

	public void setUsagruponatdesp(String usagruponatdesp) {
		this.usagruponatdesp = usagruponatdesp;
	}

	@Column(name = "INDDIAUTILDTAVENC", nullable = false, length = 1)
	public String getInddiautildtavenc() {
		return this.inddiautildtavenc;
	}

	public void setInddiautildtavenc(String inddiautildtavenc) {
		this.inddiautildtavenc = inddiautildtavenc;
	}

	@Column(name = "CODESPECIEICMSRETTRANSP", length = 6)
	public String getCodespecieicmsrettransp() {
		return this.codespecieicmsrettransp;
	}

	public void setCodespecieicmsrettransp(String codespecieicmsrettransp) {
		this.codespecieicmsrettransp = codespecieicmsrettransp;
	}

	@Column(name = "SEQPESSOAICMSRETTRANSP", precision = 8, scale = 0)
	public Integer getSeqpessoaicmsrettransp() {
		return this.seqpessoaicmsrettransp;
	}

	public void setSeqpessoaicmsrettransp(Integer seqpessoaicmsrettransp) {
		this.seqpessoaicmsrettransp = seqpessoaicmsrettransp;
	}

	@Column(name = "CODOPERACAOICMSRETTRANSP", precision = 8, scale = 0)
	public Integer getCodoperacaoicmsrettransp() {
		return this.codoperacaoicmsrettransp;
	}

	public void setCodoperacaoicmsrettransp(Integer codoperacaoicmsrettransp) {
		this.codoperacaoicmsrettransp = codoperacaoicmsrettransp;
	}

	@Column(name = "SEQPADRAOVENCTOICMSRETTRANSP", precision = 15, scale = 0)
	public Long getSeqpadraovenctoicmsrettransp() {
		return this.seqpadraovenctoicmsrettransp;
	}

	public void setSeqpadraovenctoicmsrettransp(
			Long seqpadraovenctoicmsrettransp) {
		this.seqpadraovenctoicmsrettransp = seqpadraovenctoicmsrettransp;
	}

	@Column(name = "PERCICMSRETTRANSP", precision = 5)
	public BigDecimal getPercicmsrettransp() {
		return this.percicmsrettransp;
	}

	public void setPercicmsrettransp(BigDecimal percicmsrettransp) {
		this.percicmsrettransp = percicmsrettransp;
	}

	@Column(name = "CODRECDARFPISRET", precision = 10, scale = 0)
	public Long getCodrecdarfpisret() {
		return this.codrecdarfpisret;
	}

	public void setCodrecdarfpisret(Long codrecdarfpisret) {
		this.codrecdarfpisret = codrecdarfpisret;
	}

	@Column(name = "CODRECDARFCOFINSRET", precision = 10, scale = 0)
	public Long getCodrecdarfcofinsret() {
		return this.codrecdarfcofinsret;
	}

	public void setCodrecdarfcofinsret(Long codrecdarfcofinsret) {
		this.codrecdarfcofinsret = codrecdarfcofinsret;
	}

	@Column(name = "CODRECDARFCSLLRET", precision = 10, scale = 0)
	public Long getCodrecdarfcsllret() {
		return this.codrecdarfcsllret;
	}

	public void setCodrecdarfcsllret(Long codrecdarfcsllret) {
		this.codrecdarfcsllret = codrecdarfcsllret;
	}

	@Column(name = "CODRECDARFTODOSRET", precision = 10, scale = 0)
	public Long getCodrecdarftodosret() {
		return this.codrecdarftodosret;
	}

	public void setCodrecdarftodosret(Long codrecdarftodosret) {
		this.codrecdarftodosret = codrecdarftodosret;
	}

	@Column(name = "SEQPADRAOVENCTOINSSPAT", precision = 15, scale = 0)
	public Long getSeqpadraovenctoinsspat() {
		return this.seqpadraovenctoinsspat;
	}

	public void setSeqpadraovenctoinsspat(Long seqpadraovenctoinsspat) {
		this.seqpadraovenctoinsspat = seqpadraovenctoinsspat;
	}

	@Column(name = "PERCINSSPAT", precision = 5)
	public BigDecimal getPercinsspat() {
		return this.percinsspat;
	}

	public void setPercinsspat(BigDecimal percinsspat) {
		this.percinsspat = percinsspat;
	}

	@Column(name = "CODESPECIEINSSPAT", length = 6)
	public String getCodespecieinsspat() {
		return this.codespecieinsspat;
	}

	public void setCodespecieinsspat(String codespecieinsspat) {
		this.codespecieinsspat = codespecieinsspat;
	}

	@Column(name = "SEQPESSOAINSSPAT", precision = 8, scale = 0)
	public Integer getSeqpessoainsspat() {
		return this.seqpessoainsspat;
	}

	public void setSeqpessoainsspat(Integer seqpessoainsspat) {
		this.seqpessoainsspat = seqpessoainsspat;
	}

	@Column(name = "CODOPERACAOINSSPAT", precision = 4, scale = 0)
	public Short getCodoperacaoinsspat() {
		return this.codoperacaoinsspat;
	}

	public void setCodoperacaoinsspat(Short codoperacaoinsspat) {
		this.codoperacaoinsspat = codoperacaoinsspat;
	}

	@Column(name = "INDINTEGRADTAFUTURA", length = 1)
	public String getIndintegradtafutura() {
		return this.indintegradtafutura;
	}

	public void setIndintegradtafutura(String indintegradtafutura) {
		this.indintegradtafutura = indintegradtafutura;
	}

	@Column(name = "INDCONTROLEORCAMENTARIO", length = 1)
	public String getIndcontroleorcamentario() {
		return this.indcontroleorcamentario;
	}

	public void setIndcontroleorcamentario(String indcontroleorcamentario) {
		this.indcontroleorcamentario = indcontroleorcamentario;
	}

	@Column(name = "INDUTILIZAMULTIREQNF", length = 1)
	public String getIndutilizamultireqnf() {
		return this.indutilizamultireqnf;
	}

	public void setIndutilizamultireqnf(String indutilizamultireqnf) {
		this.indutilizamultireqnf = indutilizamultireqnf;
	}

	@Column(name = "INDCONTABILIZAVLRNF", length = 1)
	public String getIndcontabilizavlrnf() {
		return this.indcontabilizavlrnf;
	}

	public void setIndcontabilizavlrnf(String indcontabilizavlrnf) {
		this.indcontabilizavlrnf = indcontabilizavlrnf;
	}

	@Column(name = "USAARVOREAUTALCADA", length = 1)
	public String getUsaarvoreautalcada() {
		return this.usaarvoreautalcada;
	}

	public void setUsaarvoreautalcada(String usaarvoreautalcada) {
		this.usaarvoreautalcada = usaarvoreautalcada;
	}

	@Column(name = "INDPERIODOORC", length = 1)
	public String getIndperiodoorc() {
		return this.indperiodoorc;
	}

	public void setIndperiodoorc(String indperiodoorc) {
		this.indperiodoorc = indperiodoorc;
	}

	@Column(name = "INDCONTROLEORC", length = 1)
	public String getIndcontroleorc() {
		return this.indcontroleorc;
	}

	public void setIndcontroleorc(String indcontroleorc) {
		this.indcontroleorc = indcontroleorc;
	}

	@Column(name = "PERCIRPESFIS", precision = 5)
	public BigDecimal getPercirpesfis() {
		return this.percirpesfis;
	}

	public void setPercirpesfis(BigDecimal percirpesfis) {
		this.percirpesfis = percirpesfis;
	}

	@Column(name = "CODESPECIEIRPESFIS", length = 6)
	public String getCodespecieirpesfis() {
		return this.codespecieirpesfis;
	}

	public void setCodespecieirpesfis(String codespecieirpesfis) {
		this.codespecieirpesfis = codespecieirpesfis;
	}

	@Column(name = "SEQPESSOAIRPESFIS", precision = 8, scale = 0)
	public Integer getSeqpessoairpesfis() {
		return this.seqpessoairpesfis;
	}

	public void setSeqpessoairpesfis(Integer seqpessoairpesfis) {
		this.seqpessoairpesfis = seqpessoairpesfis;
	}

	@Column(name = "CODOPERACAOIRPESFIS", precision = 3, scale = 0)
	public Short getCodoperacaoirpesfis() {
		return this.codoperacaoirpesfis;
	}

	public void setCodoperacaoirpesfis(Short codoperacaoirpesfis) {
		this.codoperacaoirpesfis = codoperacaoirpesfis;
	}

	@Column(name = "SEQPADRAOVENCTOIRPESFIS", precision = 15, scale = 0)
	public Long getSeqpadraovenctoirpesfis() {
		return this.seqpadraovenctoirpesfis;
	}

	public void setSeqpadraovenctoirpesfis(Long seqpadraovenctoirpesfis) {
		this.seqpadraovenctoirpesfis = seqpadraovenctoirpesfis;
	}

	@Column(name = "PERCINSSPESFIS", precision = 5)
	public BigDecimal getPercinsspesfis() {
		return this.percinsspesfis;
	}

	public void setPercinsspesfis(BigDecimal percinsspesfis) {
		this.percinsspesfis = percinsspesfis;
	}

	@Column(name = "CODESPECIEINSSPESFIS", length = 6)
	public String getCodespecieinsspesfis() {
		return this.codespecieinsspesfis;
	}

	public void setCodespecieinsspesfis(String codespecieinsspesfis) {
		this.codespecieinsspesfis = codespecieinsspesfis;
	}

	@Column(name = "SEQPESSOAINSSPESFIS", precision = 8, scale = 0)
	public Integer getSeqpessoainsspesfis() {
		return this.seqpessoainsspesfis;
	}

	public void setSeqpessoainsspesfis(Integer seqpessoainsspesfis) {
		this.seqpessoainsspesfis = seqpessoainsspesfis;
	}

	@Column(name = "CODOPERACAOINSSPESFIS", precision = 3, scale = 0)
	public Short getCodoperacaoinsspesfis() {
		return this.codoperacaoinsspesfis;
	}

	public void setCodoperacaoinsspesfis(Short codoperacaoinsspesfis) {
		this.codoperacaoinsspesfis = codoperacaoinsspesfis;
	}

	@Column(name = "SEQPADRAOVENCTOINSSPESFIS", precision = 15, scale = 0)
	public Long getSeqpadraovenctoinsspesfis() {
		return this.seqpadraovenctoinsspesfis;
	}

	public void setSeqpadraovenctoinsspesfis(Long seqpadraovenctoinsspesfis) {
		this.seqpadraovenctoinsspesfis = seqpadraovenctoinsspesfis;
	}

	@Column(name = "PROCORCPERCENTUAL", length = 1)
	public String getProcorcpercentual() {
		return this.procorcpercentual;
	}

	public void setProcorcpercentual(String procorcpercentual) {
		this.procorcpercentual = procorcpercentual;
	}

}
