package br.com.seta.processo.entity;

import java.math.BigDecimal;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrvProdutotrib generated by hbm2java
 */
@Entity
@Table(name = "ORV_PRODUTOTRIB")


@Cacheable(true)
public class OrvProdutotribEntity implements java.io.Serializable {	
	private static final long serialVersionUID = 1L;
	
	@Id
	private BigDecimal seqproduto;
	private String codproduto;
	private String descricao;
	private short nroempresa;
	private String indusanfdespesa;
	private BigDecimal aliqipi;
	private BigDecimal aliqicms;
	private BigDecimal percredbaseicms;
	private String vlrbaseicmsst;
	private String codncm;
	private String codstf;
	private String unidadepadrao;
	private Character isentopiscofins;
	private Character indisentodebpiscofins;
	private Short versaoprod;
	private String servico;
	private Character veiculo;
	private BigDecimal seqfornecedor;
	private String codobservacao;
	private BigDecimal codnatrec;
	private BigDecimal aliqpadraoicms;
	private Short codservico;
	private Short subitemcodservico;
	private int nrotributacao;
	private String situacaonfipi;

	public OrvProdutotribEntity() {
	}

	public OrvProdutotribEntity(BigDecimal seqproduto, String descricao,
			short nroempresa, BigDecimal aliqicms, BigDecimal percredbaseicms,
			BigDecimal seqfornecedor, int nrotributacao) {
		this.seqproduto = seqproduto;
		this.descricao = descricao;
		this.nroempresa = nroempresa;
		this.aliqicms = aliqicms;
		this.percredbaseicms = percredbaseicms;
		this.seqfornecedor = seqfornecedor;
		this.nrotributacao = nrotributacao;
	}

	public OrvProdutotribEntity(BigDecimal seqproduto, String codproduto,
			String descricao, short nroempresa, String indusanfdespesa,
			BigDecimal aliqipi, BigDecimal aliqicms,
			BigDecimal percredbaseicms, String vlrbaseicmsst, String codncm,
			String codstf, String unidadepadrao, Character isentopiscofins,
			Character indisentodebpiscofins, Short versaoprod, String servico,
			Character veiculo, BigDecimal seqfornecedor, String codobservacao,
			BigDecimal codnatrec, BigDecimal aliqpadraoicms, Short codservico,
			Short subitemcodservico, int nrotributacao, String situacaonfipi) {
		this.seqproduto = seqproduto;
		this.codproduto = codproduto;
		this.descricao = descricao;
		this.nroempresa = nroempresa;
		this.indusanfdespesa = indusanfdespesa;
		this.aliqipi = aliqipi;
		this.aliqicms = aliqicms;
		this.percredbaseicms = percredbaseicms;
		this.vlrbaseicmsst = vlrbaseicmsst;
		this.codncm = codncm;
		this.codstf = codstf;
		this.unidadepadrao = unidadepadrao;
		this.isentopiscofins = isentopiscofins;
		this.indisentodebpiscofins = indisentodebpiscofins;
		this.versaoprod = versaoprod;
		this.servico = servico;
		this.veiculo = veiculo;
		this.seqfornecedor = seqfornecedor;
		this.codobservacao = codobservacao;
		this.codnatrec = codnatrec;
		this.aliqpadraoicms = aliqpadraoicms;
		this.codservico = codservico;
		this.subitemcodservico = subitemcodservico;
		this.nrotributacao = nrotributacao;
		this.situacaonfipi = situacaonfipi;
	}

	@Column(name = "SEQPRODUTO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSeqproduto() {
		return this.seqproduto;
	}

	public void setSeqproduto(BigDecimal seqproduto) {
		this.seqproduto = seqproduto;
	}

	@Column(name = "CODPRODUTO", length = 14)
	public String getCodproduto() {
		return this.codproduto;
	}

	public void setCodproduto(String codproduto) {
		this.codproduto = codproduto;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 50)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "NROEMPRESA", nullable = false, precision = 3, scale = 0)
	public short getNroempresa() {
		return this.nroempresa;
	}

	public void setNroempresa(short nroempresa) {
		this.nroempresa = nroempresa;
	}

	@Column(name = "INDUSANFDESPESA", length = 1)
	public String getIndusanfdespesa() {
		return this.indusanfdespesa;
	}

	public void setIndusanfdespesa(String indusanfdespesa) {
		this.indusanfdespesa = indusanfdespesa;
	}

	@Column(name = "ALIQIPI", precision = 22, scale = 0)
	public BigDecimal getAliqipi() {
		return this.aliqipi;
	}

	public void setAliqipi(BigDecimal aliqipi) {
		this.aliqipi = aliqipi;
	}

	@Column(name = "ALIQICMS", nullable = false, precision = 4)
	public BigDecimal getAliqicms() {
		return this.aliqicms;
	}

	public void setAliqicms(BigDecimal aliqicms) {
		this.aliqicms = aliqicms;
	}

	@Column(name = "PERCREDBASEICMS", nullable = false, precision = 7, scale = 4)
	public BigDecimal getPercredbaseicms() {
		return this.percredbaseicms;
	}

	public void setPercredbaseicms(BigDecimal percredbaseicms) {
		this.percredbaseicms = percredbaseicms;
	}

	@Column(name = "VLRBASEICMSST", length = 0)
	public String getVlrbaseicmsst() {
		return this.vlrbaseicmsst;
	}

	public void setVlrbaseicmsst(String vlrbaseicmsst) {
		this.vlrbaseicmsst = vlrbaseicmsst;
	}

	@Column(name = "CODNCM", length = 10)
	public String getCodncm() {
		return this.codncm;
	}

	public void setCodncm(String codncm) {
		this.codncm = codncm;
	}

	@Column(name = "CODSTF", length = 3)
	public String getCodstf() {
		return this.codstf;
	}

	public void setCodstf(String codstf) {
		this.codstf = codstf;
	}

	@Column(name = "UNIDADEPADRAO", length = 2)
	public String getUnidadepadrao() {
		return this.unidadepadrao;
	}

	public void setUnidadepadrao(String unidadepadrao) {
		this.unidadepadrao = unidadepadrao;
	}

	@Column(name = "ISENTOPISCOFINS", length = 1)
	public Character getIsentopiscofins() {
		return this.isentopiscofins;
	}

	public void setIsentopiscofins(Character isentopiscofins) {
		this.isentopiscofins = isentopiscofins;
	}

	@Column(name = "INDISENTODEBPISCOFINS", length = 1)
	public Character getIndisentodebpiscofins() {
		return this.indisentodebpiscofins;
	}

	public void setIndisentodebpiscofins(Character indisentodebpiscofins) {
		this.indisentodebpiscofins = indisentodebpiscofins;
	}

	@Column(name = "VERSAOPROD", precision = 3, scale = 0)
	public Short getVersaoprod() {
		return this.versaoprod;
	}

	public void setVersaoprod(Short versaoprod) {
		this.versaoprod = versaoprod;
	}

	@Column(name = "SERVICO", length = 1)
	public String getServico() {
		return this.servico;
	}

	public void setServico(String servico) {
		this.servico = servico;
	}

	@Column(name = "VEICULO", length = 1)
	public Character getVeiculo() {
		return this.veiculo;
	}

	public void setVeiculo(Character veiculo) {
		this.veiculo = veiculo;
	}

	@Column(name = "SEQFORNECEDOR", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSeqfornecedor() {
		return this.seqfornecedor;
	}

	public void setSeqfornecedor(BigDecimal seqfornecedor) {
		this.seqfornecedor = seqfornecedor;
	}

	@Column(name = "CODOBSERVACAO", length = 250)
	public String getCodobservacao() {
		return this.codobservacao;
	}

	public void setCodobservacao(String codobservacao) {
		this.codobservacao = codobservacao;
	}

	@Column(name = "CODNATREC", precision = 22, scale = 0)
	public BigDecimal getCodnatrec() {
		return this.codnatrec;
	}

	public void setCodnatrec(BigDecimal codnatrec) {
		this.codnatrec = codnatrec;
	}

	@Column(name = "ALIQPADRAOICMS", precision = 15)
	public BigDecimal getAliqpadraoicms() {
		return this.aliqpadraoicms;
	}

	public void setAliqpadraoicms(BigDecimal aliqpadraoicms) {
		this.aliqpadraoicms = aliqpadraoicms;
	}

	@Column(name = "CODSERVICO", precision = 4, scale = 0)
	public Short getCodservico() {
		return this.codservico;
	}

	public void setCodservico(Short codservico) {
		this.codservico = codservico;
	}

	@Column(name = "SUBITEMCODSERVICO", precision = 4, scale = 0)
	public Short getSubitemcodservico() {
		return this.subitemcodservico;
	}

	public void setSubitemcodservico(Short subitemcodservico) {
		this.subitemcodservico = subitemcodservico;
	}

	@Column(name = "NROTRIBUTACAO", nullable = false, precision = 5, scale = 0)
	public int getNrotributacao() {
		return this.nrotributacao;
	}

	public void setNrotributacao(int nrotributacao) {
		this.nrotributacao = nrotributacao;
	}

	@Column(name = "SITUACAONFIPI", length = 3)
	public String getSituacaonfipi() {
		return this.situacaonfipi;
	}

	public void setSituacaonfipi(String situacaonfipi) {
		this.situacaonfipi = situacaonfipi;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OrvProdutotribEntity other = (OrvProdutotribEntity) obj;
		if (aliqicms == null) {
			if (other.aliqicms != null)
				return false;
		} else if (!aliqicms.equals(other.aliqicms))
			return false;
		if (aliqipi == null) {
			if (other.aliqipi != null)
				return false;
		} else if (!aliqipi.equals(other.aliqipi))
			return false;
		if (aliqpadraoicms == null) {
			if (other.aliqpadraoicms != null)
				return false;
		} else if (!aliqpadraoicms.equals(other.aliqpadraoicms))
			return false;
		if (codnatrec == null) {
			if (other.codnatrec != null)
				return false;
		} else if (!codnatrec.equals(other.codnatrec))
			return false;
		if (codncm == null) {
			if (other.codncm != null)
				return false;
		} else if (!codncm.equals(other.codncm))
			return false;
		if (codobservacao == null) {
			if (other.codobservacao != null)
				return false;
		} else if (!codobservacao.equals(other.codobservacao))
			return false;
		if (codproduto == null) {
			if (other.codproduto != null)
				return false;
		} else if (!codproduto.equals(other.codproduto))
			return false;
		if (codservico == null) {
			if (other.codservico != null)
				return false;
		} else if (!codservico.equals(other.codservico))
			return false;
		if (codstf == null) {
			if (other.codstf != null)
				return false;
		} else if (!codstf.equals(other.codstf))
			return false;
		if (descricao == null) {
			if (other.descricao != null)
				return false;
		} else if (!descricao.equals(other.descricao))
			return false;
		if (indisentodebpiscofins == null) {
			if (other.indisentodebpiscofins != null)
				return false;
		} else if (!indisentodebpiscofins.equals(other.indisentodebpiscofins))
			return false;
		if (indusanfdespesa == null) {
			if (other.indusanfdespesa != null)
				return false;
		} else if (!indusanfdespesa.equals(other.indusanfdespesa))
			return false;
		if (isentopiscofins == null) {
			if (other.isentopiscofins != null)
				return false;
		} else if (!isentopiscofins.equals(other.isentopiscofins))
			return false;
		if (nroempresa != other.nroempresa)
			return false;
		if (nrotributacao != other.nrotributacao)
			return false;
		if (percredbaseicms == null) {
			if (other.percredbaseicms != null)
				return false;
		} else if (!percredbaseicms.equals(other.percredbaseicms))
			return false;
		if (seqfornecedor == null) {
			if (other.seqfornecedor != null)
				return false;
		} else if (!seqfornecedor.equals(other.seqfornecedor))
			return false;
		if (seqproduto == null) {
			if (other.seqproduto != null)
				return false;
		} else if (!seqproduto.equals(other.seqproduto))
			return false;
		if (servico == null) {
			if (other.servico != null)
				return false;
		} else if (!servico.equals(other.servico))
			return false;
		if (situacaonfipi == null) {
			if (other.situacaonfipi != null)
				return false;
		} else if (!situacaonfipi.equals(other.situacaonfipi))
			return false;
		if (subitemcodservico == null) {
			if (other.subitemcodservico != null)
				return false;
		} else if (!subitemcodservico.equals(other.subitemcodservico))
			return false;
		if (unidadepadrao == null) {
			if (other.unidadepadrao != null)
				return false;
		} else if (!unidadepadrao.equals(other.unidadepadrao))
			return false;
		if (veiculo == null) {
			if (other.veiculo != null)
				return false;
		} else if (!veiculo.equals(other.veiculo))
			return false;
		if (versaoprod == null) {
			if (other.versaoprod != null)
				return false;
		} else if (!versaoprod.equals(other.versaoprod))
			return false;
		if (vlrbaseicmsst == null) {
			if (other.vlrbaseicmsst != null)
				return false;
		} else if (!vlrbaseicmsst.equals(other.vlrbaseicmsst))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((aliqicms == null) ? 0 : aliqicms.hashCode());
		result = prime * result + ((aliqipi == null) ? 0 : aliqipi.hashCode());
		result = prime * result
				+ ((aliqpadraoicms == null) ? 0 : aliqpadraoicms.hashCode());
		result = prime * result
				+ ((codnatrec == null) ? 0 : codnatrec.hashCode());
		result = prime * result + ((codncm == null) ? 0 : codncm.hashCode());
		result = prime * result
				+ ((codobservacao == null) ? 0 : codobservacao.hashCode());
		result = prime * result
				+ ((codproduto == null) ? 0 : codproduto.hashCode());
		result = prime * result
				+ ((codservico == null) ? 0 : codservico.hashCode());
		result = prime * result + ((codstf == null) ? 0 : codstf.hashCode());
		result = prime * result
				+ ((descricao == null) ? 0 : descricao.hashCode());
		result = prime
				* result
				+ ((indisentodebpiscofins == null) ? 0 : indisentodebpiscofins
						.hashCode());
		result = prime * result
				+ ((indusanfdespesa == null) ? 0 : indusanfdespesa.hashCode());
		result = prime * result
				+ ((isentopiscofins == null) ? 0 : isentopiscofins.hashCode());
		result = prime * result + nroempresa;
		result = prime * result + nrotributacao;
		result = prime * result
				+ ((percredbaseicms == null) ? 0 : percredbaseicms.hashCode());
		result = prime * result
				+ ((seqfornecedor == null) ? 0 : seqfornecedor.hashCode());
		result = prime * result
				+ ((seqproduto == null) ? 0 : seqproduto.hashCode());
		result = prime * result + ((servico == null) ? 0 : servico.hashCode());
		result = prime * result
				+ ((situacaonfipi == null) ? 0 : situacaonfipi.hashCode());
		result = prime
				* result
				+ ((subitemcodservico == null) ? 0 : subitemcodservico
						.hashCode());
		result = prime * result
				+ ((unidadepadrao == null) ? 0 : unidadepadrao.hashCode());
		result = prime * result + ((veiculo == null) ? 0 : veiculo.hashCode());
		result = prime * result
				+ ((versaoprod == null) ? 0 : versaoprod.hashCode());
		result = prime * result
				+ ((vlrbaseicmsst == null) ? 0 : vlrbaseicmsst.hashCode());
		return result;
	}


}
